@receiverName=Receiver-{{$randomInt 20001 30000}}
@newEmail = user-{{$randomInt 20001 30000}}@skyfire.xyz
@amount=.00{{$randomInt 1001 5000}}

###
# health
GET {{url}}/health

###
# ADMIN Impersonate Session
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{newEmail}}"
}

###
# Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create Main Wallet
POST {{url}}/users/main-wallet
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "userType": "Receiver",
  "isInternal": true
}

###
# Patch UserName
# @name meResponse
PATCH {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "username": "{{receiverName}}"
}

###
# Get My Balance
# @name myWalletsResponse
GET {{url}}/wallet/balance
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Make Payment To New Receiver
# @name payment
POST {{url}}/payment
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "externalId": "{{$guid}}",
  "payments": [
    {
      "receiverUsername": "{{meResponse.response.body.username}}",
      "amount": "{{amount}}",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    }
  ]
}