@amount=.00{{$randomInt 1001 5000}}

###
# Make Payment
# @name payment
POST {{url}}/payment
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "externalId": "{{$guid}}",
  "payments": [
    {
      "receiverUsername": "OpenAI",
      "amount": "{{amount}}",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    },
    {
      "receiverUsername": "OpenRouter",
      "amount": "{{amount}}",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    }
  ]
}
