@username=janwilmake
@email=jan@wilmake.com
@orgName = ExampleOrg-{{$randomInt 20001 30000}}
@newEmail = user-{{$randomInt 20001 30000}}@skyfire.xyz
@amount=.00{{$randomInt 1001 5000}}

###
# Create Sender  
# @name createdEnterpriseAdmin
POST {{url}}/admin/users
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "userType": "Receiver",
  "cost": 1000,
  "isEnterpriseAdmin": true
}

###
# ADMIN Impersonate Session
# @name entAdminSessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{email}}"
}

###
# Create API Key
# @name entAdminApikey
POST {{url}}/users/api-keys
Authorization: Bearer {{entAdminSessionTokenResponse.response.body.sessionToken}}

###
# ENTERPRISE ADMIN Add Organization
# @name orgResponse
POST {{url}}/enterprise/admin/organizations
skyfire-api-key: {{entAdminApikey.response.body.apiKey}}
content-type: application/json

{
    "name": "{{orgName}}"
}

###
# ENTERPRISE ADMIN Add Wallet to Organization
# @name walletResponse
POST {{url}}/enterprise/admin/organizations/wallet
skyfire-api-key: {{entAdminApikey.response.body.apiKey}}
content-type: application/json

{
    "organizationName": "{{orgResponse.response.body.name}}",
    "walletType": "Sender"
}

###
# ENTERPRISE ADMIN Add New User
# @name newUserResponse
POST {{url}}/enterprise/admin/users/organizationUser
skyfire-api-key: {{entAdminApikey.response.body.apiKey}}
content-type: application/json

{
    "email": "{{newEmail}}",
    "organizationName": "{{orgResponse.response.body.name}}",
    "attributes": {
        "firstName": "Alice",
        "lastName": "Smith",
        "phone": "1234567890",
        "address": "123 Main St",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94105",
        "country": "USA",
        "carbonArcID": "1234567890"
    }
}

###
# Get User Full Data 
# @name createdUser
GET {{url}}/admin/users/by-email/{{newUserResponse.response.body.user.email}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# ADMIN Impersonate Session for New User
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{newUserResponse.response.body.user.email}}"
}

###
# USER: Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# USER: Check organization wallet balance
GET {{url}}/wallet/balance
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# ENTERPRISE ADMIN Get User
# @name getUserResponse
GET {{url}}/enterprise/admin/users/organizationUser/{{newUserResponse.response.body.user.email}}
skyfire-api-key: {{entAdminApikey.response.body.apiKey}}
content-type: application/json

###
# USER: Get All Org Wallets Dashboard
# @name meResponse
GET {{url}}/wallet/organizations
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create API-Key for user
# @name newUserApiKeyResponse
POST {{url}}/enterprise/admin/users/api-keys
skyfire-api-key: {{entAdminApikey.response.body.apiKey}}
content-type: application/json

{
    "email": "{{newUserResponse.response.body.user.email}}"
}

###
# Make Group Payment
# @name payment
POST {{url}}/payment
skyfire-api-key: {{newUserApiKeyResponse.response.body.apiKey}}
content-type: application/json

{
  "externalId": "{{$guid}}",
  "payments": [
    {
      "receiverUsername": "{{username}}",
      "amount": "{{amount}}",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    }
  ]
}
