@newEmail = user-{{$randomInt 20001 30000}}@skyfire.xyz

###
# health
GET {{url}}/health

###
# ADMIN Impersonate Session
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{newEmail}}"
}

###
# Start on-boarding
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create Main Wallet
POST {{url}}/users/main-wallet
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "userType": "Sender"
}

###
# Patch User
PATCH {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "username": "{{meResponse.response.body.email}}",
  "isOnboarded": true

}

###
# Check balance of wallet
GET {{url}}/wallet/balance
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create API Key
# @name apikey
POST {{url}}/users/api-keys
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}

###
# OpenRouter
# @name receiverResponse
POST {{proxyUrl}}/proxy/openrouter/v1/chat/completions
skyfire-api-key: {{apikey.response.body.apiKey}}
content-type: application/json

{
  "model": "openai/gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "What is the meaning of life?"
    }
  ]
}

###
# Get Claim by ReferenceID
# @name claimByReferenceId
GET {{url}}/wallet/claimByReferenceId/{{receiverResponse.response.headers.Skyfire-Payment-Reference-ID}}
skyfire-api-key: {{apikey.response.body.apiKey}}
content-type: application/json

###
# Admin Redeem
POST {{url}}/admin/wallet/redeem
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "sourceAddress": "{{claimByReferenceId.response.body.sourceAddress}}",
  "destinationAddress": "{{claimByReferenceId.response.body.destinationAddress}}",
  "network": "{{claimByReferenceId.response.body.network}}"
}

###
# Check claims
GET {{url}}/wallet/claims
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}

###
# Check Redemptions
GET {{url}}/wallet/redemptions
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
