@apiClientIdSandbox={{$dotenv RELOADLY_API_CLIENT_ID_SANDBOX}}
@apiSecretSandbox={{$dotenv RELOADLY_API_SECRET_SANDBOX}}
@apiClientIdProd={{$dotenv RELOADLY_API_CLIENT_ID_PROD}}
@apiSecretProd={{$dotenv RELOADLY_API_SECRET_PROD}}
@reloadlyUrlSandbox={{$dotenv RELOADLY_URL_SANDBOX}}
@reloadlyUrlProd={{$dotenv RELAODLY_URL_PROD}}
@apiClientId={{apiClientIdProd}}
@apiSecret={{apiSecretProd}}
@reloadlyUrl={{reloadlyUrlProd}}
# @apiClientId={{apiClientIdSandbox}}
# @apiSecret={{apiSecretSandbox}}
# @reloadlyUrl={{reloadlyUrlSandbox}}

###
# Get access token
# @name accessToken
POST https://auth.reloadly.com/oauth/token 
Content-Type: application/json

{
  "client_id": "{{apiClientId}}",
  "client_secret": "{{apiSecret}}",
  "grant_type": "client_credentials",
  "audience": "{{reloadlyUrl}}"
}

###
# Countries
# @name countries
GET {{reloadlyUrl}}/countries
Authorization: Bearer {{accessToken.response.body.access_token}}
Content-Type: application/json

###
# Products By Country
GET {{reloadlyUrl}}/countries/US/products
Accept: application/com.reloadly.giftcards-v1+json
Authorization: Bearer {{accessToken.response.body.access_token}}

###
# Purchase Gift Card
# @name purchaseGiftCard
POST {{reloadlyUrl}}/orders
Authorization: Bearer {{accessToken.response.body.access_token}}
Content-Type: application/json

{
  "productId": 5,
  "unitPrice": 1,
  "countryCode": "US",
  "quantity": 1,
  "customIdentifier": "{{$guid}}"
}

###
# Purchase Gift Card
# @name purchaseGiftCard
POST {{reloadlyUrl}}/orders
Authorization: Bearer {{accessToken.response.body.access_token}}
Content-Type: application/json

{
  "productId": 5,
  "unitPrice": 1,
  "countryCode": "US",
  "quantity": 1,
  "customIdentifier": "{{$guid}}"
}

###
# Get Redeem Instructions
GET {{reloadlyUrl}}/brands/{{purchaseGiftCard.response.body.product.brand.brandId}}/redeem-instructions
Authorization: Bearer {{accessToken.response.body.access_token}}
Content-Type: application/json

###
# Get Redeem Code
GET {{reloadlyUrl}}/orders/transactions/761328/cards
Authorization: Bearer {{accessToken.response.body.access_token}}
Content-Type: application/json

###
# Products
GET {{reloadlyUrl}}/products?size=1000&page=1&productName=amazon&includeRange=true&includeFixed=true
Accept: application/com.reloadly.giftcards-v1+json
Authorization: Bearer {{accessToken.response.body.access_token}}

### Test Skyfire APIs

###
# Purchase Gift Card
# @name purchaseGiftCard
POST {{url}}/receivers/reloadly/gift-card
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "recipientEmail": "hieu@skyfire.xyz",
  "countryCode": "US",
  "amount": 1
}

###
# Purchase Gift Card
# @name purchaseGiftCard
GET {{url}}/receivers/reloadly/redeem-code/761536
skyfire-api-key: {{hieuApiKey}}
content-type: application/json
