###
# API Ninja
# @name receiverResponse
GET {{proxyUrl}}/proxy/api-ninja/v1/stockprice?ticker=GOOGL
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# ADMIN API
# Flush Caches
GET {{url}}/admin/users/flush-caches
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# Create API Ninja Receiver, coin amount should 
# @name createdUser
POST {{url}}/admin/users
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "username": "API Ninja",
  "email": "apininja@skyfire.xyz",
  "userType": "Receiver",
  "cost": 1005,
  "basePath": "/api-ninja",
  "proxyUrl": "https://api.api-ninjas.com/",
  "isProxy": true,
  "headers": {
    "x-api-key": "QFNL5gV/cZ3iix87FI+/Dw==xa6urt3xiacQ5Z9W"
  }
}


###
# Create Perplexity Receiver, coin amount should 
# @name createdUser
POST {{url}}/admin/users
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "username": "Perplexity",
  "email": "perplexity@skyfire.xyz",
  "userType": "Receiver",
  "cost": 1001,
  "basePath": "/perplexity",
  "proxyUrl": "https://api.perplexity.ai/",
  "isProxy": true,
  "headers": {
    "Authorization": "Bearer {{$dotenv PERPLEXITY_API_KEY}}"
  },
  "allowList": [
    "/chat/completions"
  ],
  "blockList": [
    "/chat/completions/foo"
  ],
  "freeList": [
    "/chat/completions"
  ]
}

###
# Patch Receiver 
# @name createdUser
PATCH {{url}}/admin/users
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{createdUser.response.body.email}}",
  "basePath": "/perplexity",
  "proxyUrl": "https://api.perplexity.ai/",
  "isProxy": true,
  "headers": {
    "Authorization": "Bearer {{$dotenv PERPLEXITY_API_KEY}}"
  },
  "allowList": [
    "/chat/completions"
  ],
  "blockList": [
    "/chat/completions/foo"
  ],
  "freeList": [
    "/chat/completions"
  ]
}

###
# Perplexity
# @name receiverResponse
POST {{proxyUrl}}/proxy/perplexity/chat/completions/
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "model": "sonar-reasoning",
  "messages": [
    {
      "role": "user",
      "content": "What is the meaning of life?"
    }
  ]
}

###
# API Ninja
# @name receiverResponse
GET {{proxyUrl}}/proxy/api-ninja2/v1/stockprice?ticker=GOOGL
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# Patch API Ninja Receiver 
# @name createdUser
PATCH {{url}}/admin/users
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "apininja@skyfire.xyz",
  "isProxy": true,
  "basePath": "/api-ninja",
  "proxyUrl": "https://api.api-ninjas.com/",
  "isProxy": true,
  "headers": {
    "x-api-key": "{{$dotenv API_NINJA_API_KEY}}"
  }
}

###
# Patch Perplexit Receiver 
# @name createdUser
PATCH {{url}}/admin/users
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "perplexity@skyfire.xyz",
  "isProxy": true,
  "basePath": "/perplexity",
  "proxyUrl": "https://api.perplexity.ai/",
  "isProxy": true,
  "headers": {
    "Authorization": "Bearer {{$dotenv PERPLEXITY_API_KEY}}"
  },
  "allowList": [
    "/chat/completions"
  ]
}