To fund your wallets programmatically, submit a request to POST /v1/faucet/drips.

### 
# Wallet: hieuta.eth
POST https://api.circle.com/v1/faucet/drips
Content-Type: application/json
Authorization: Bearer TEST_API_KEY:3a1842fb65bb35d0a69b84f3c6e4e29d:e7d506b6d51c63555e5d6e592fe39a0a

{
    "address": "0x2577CB53c34E997EAE233BdEb8029a2B6a990C24",
    "blockchain": "ETH-SEPOLIA",
    "native": true,
    "usdc": true,
    "eurc": false
}