@notDiamondBaseUrl=https://api.notdiamond.ai

###
# Get Route
POST {{notDiamondBaseUrl}}/v2/modelRouter/modelSelect
Content-Type: application/json
Authorization: Bearer {{notDiamondApiKey}}

{
  "messages": [
    {
        "role": "user", 
        "content": "What is the meaning of life?"
    }
  ],
  "tradeoff": "cost",
  "llm_providers": [
    {
      "provider": "openai",
      "model": "gpt-3.5-turbo"
    },
    {
      "provider": "openai",
      "model": "gpt-4-1106-preview"
    },
    {
      "provider": "anthropic",
      "model": "claude-3-opus-20240229"
    }
  ],
  "max_model_depth": 2
}
