@email = dev1@skyfire.xyz
@orgName = Dev1 Org {{$randomInt 20001 30000}}
@newEmail = user-{{$randomInt 20001 30000}}@skyfire.xyz

###
# ADMIN Impersonate Session
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "hieu@skyfire.xyz"
}

###
# ADMIN Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# ADMIN Get User By Email
GET {{url}}/admin/users/by-email/hieu@skyfire.xyz
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# ENTERPRISE ADMIN Add Organization
# @name orgResponse
POST {{url}}/admin/enterprise/organizations
skyfire-api-key: {{apiKey}}
content-type: application/json

{
    "name": "{{orgName}}"
}

###
# ENTERPRISE ADMIN Get Organizations
# @name getOrgResponse
GET {{url}}/admin/enterprise/organizations
skyfire-api-key: {{apiKey}}
content-type: application/json

###
# ENTERPRISE ADMIN Get Organizations
# @name getOrgResponse
GET {{url}}/admin/enterprise/organizations/id/{{orgResponse.response.body.id}}
skyfire-api-key: {{apiKey}}
content-type: application/json

###
# ENTERPRISE ADMIN Add New User 3X
# @name addUserResponse
POST {{url}}/enterprise/admin/users/organizationUser
skyfire-api-key: {{apiKey}}
content-type: application/json

{
    "email": "{{newEmail}}",
    "organizationName": "{{orgResponse.response.body.name}}",
    "attributes": {
        "firstName": "Hieu",
        "lastName": "Ta",
        "phone": "1234567890",
        "address": "123 Main St",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94105",
        "country": "USA",
        "carbonArcID": "1234567890"
    }
}

###
# ENTERPRISE ADMIN Add Wallet to Organization 2X
POST {{url}}/admin/enterprise/organizations/wallet
skyfire-api-key: {{apiKey}}
content-type: application/json

{
    "organizationName": "{{orgResponse.response.body.name}}",
    "walletType": "Sender",
    "network": "coinbase_testnet"
}

###
# ENTERPRISE ADMIN Get Organizations
# @name getOrgResponse
GET {{url}}/admin/enterprise/organizations/id/{{orgResponse.response.body.id}}
skyfire-api-key: {{apiKey}}
content-type: application/json

###
# ENTERPRISE ADMIN Get User
# @name getUserResponse
GET {{url}}/enterprise/admin/users/organizationUser/{{addUserResponse.response.body.email}}
skyfire-api-key: {{apiKey}}
content-type: application/json

###
# ENTERPRISE ADMIN Delete Organization with Admin Key
DELETE {{url}}/admin/organizations/id/{{orgResponse.response.body.id}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
