@newEmail = user-{{$randomInt 20001 30000}}@skyfire.xyz

###
# health
GET {{url}}/health

###
# ADMIN Impersonate Session
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{newEmail}}"
}

###
# Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create Primary Wallet
# @name primaryWalletResponse
POST {{url}}/admin/wallet/primary-eth-wallet
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{meResponse.response.body.email}}",
  "userType": "Sender",
  "network": "{{networkPT}}"
}

###
# Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Get My Wallets
# @name myWalletsResponse
GET {{url}}/admin/wallet/email/{{meResponse.response.body.email}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# Get My Wallet Balances for Address
# @name myWalletsResponseBalance
GET {{url}}/admin/wallet/balance/email/{{meResponse.response.body.email}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# Switch Wallet
GET {{url}}/admin/wallet/switch-default-wallet/id/{{myWalletsResponse.response.body.wallets[0].id}}
skyfire-api-key: {{hieuApiKey}}


###
# Create Secondary Wallet
# @name secondWalletResponse
POST {{url}}/admin/wallet/auxiliary-eth-wallet
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{meResponse.response.body.email}}",
  "walletAddress": "{{myWalletsResponse.response.body.wallets[0].walletAddress}}",
  "network": "polygon_hardhat_mainnet"
}

###
# Update Wallet
# @name updateWalletResponse
POST {{url}}/wallet/update
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "walletId": "{{meResponse.response.body.mainWallet.id}}",
  "walletName": "Main",
  "network": "coinbase_hardhat_mainnet"
}

###
# Create API Key
# @name apikey
POST {{url}}/users/api-keys
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}

###
# OpenRouter
# @name receiverResponse
POST {{proxyUrl}}/proxy/openrouter/v1/chat/completions
skyfire-api-key: {{apikey.response.body.apiKey}}
content-type: application/json

{
  "model": "openai/gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "What is the meaning of life?"
    }
  ]
}

###
# Get Claim by ReferenceID
GET {{url}}/wallet/claimByReferenceId/{{receiverResponse.response.headers.Skyfire-Payment-Reference-ID}}
skyfire-api-key: {{apikey.response.body.apiKey}}
content-type: application/json

###
# Get Wallets
GET {{url}}/admin/wallet/email/{{meResponse.response.body.email}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# Get claims
GET {{url}}/wallet/claims
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Admin Redeem
POST {{url}}/admin/wallet/redeem
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "sourceAddress": "{{meResponse.response.body.walletAddress}}",
  "destinationAddress": "asdf"
}
