@refID={{$guid}}
@receiverName=OpenRouter
@amount=.00{{$randomInt 1001 5000}}
@newEmail = user-{{$randomInt 20001 30000}}@skyfire.xyz

###
# health
GET {{url}}/health

###
# ADMIN Impersonate Session
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{newEmail}}"
}

###
# Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create Main Wallet
POST {{url}}/users/main-wallet
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "userType": "Sender"
}

###
# Get My Balance
# @name myWalletsResponse
GET {{url}}/wallet/balance
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Create API Key
# @name apikey
POST {{url}}/users/api-keys
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}

###
# Make Payment - SHOULD FAIL
# @name payment
POST {{url}}/payment
skyfire-api-key: {{apikey.response.body.apiKey}}
content-type: application/json

{
  "externalId": "{{$guid}}",
  "payments": [
    {
      "receiverUsername": "OpenAI",
      "amount": ".000001",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    },
    {
      "receiverUsername": "OpenRouter",
      "amount": "10",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    }
  ]
}

###
# Make Payment - SHOULD SUCCEED
# @name payment
POST {{url}}/payment
skyfire-api-key: {{apikey.response.body.apiKey}}
content-type: application/json

{
  "externalId": "{{$guid}}",
  "payments": [
    {
      "receiverUsername": "OpenAI",
      "amount": ".001",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    },
    {
      "receiverUsername": "OpenRouter",
      "amount": ".001",
      "data": {
        "foo": "1234",
        "bar": "5678",
        "baz": "91011"
      }
    }
  ]
}

###
# ENTERPRISE ADMIN: Validate Payment
GET {{url}}/enterprise/admin/payments/validate?externalId={{payment.response.body.claimGroup.externalId}}&senderEmail=hieu@skyfire.xyz
skyfire-api-key: {{hieuApiKey}}
content-type: application/json


###
# ADMIN: Get Payment
GET {{url}}/admin/payments/validate?externalId={{payment.response.body.claimGroup.externalId}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json
