@newEmail = user-29962@skyfire.xyz

###
# ADMIN Impersonate Session
# @name sessionTokenResponse
POST {{url}}/admin/users/create-session
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

{
  "email": "{{newEmail}}"
}

###
# Me Response
# @name meResponse
GET {{url}}/users/me
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

###
# Get User Full Data 
# @name createdUser
GET {{url}}/admin/users/by-email/{{meResponse.response.body.email}}
skyfire-api-key: {{hieuApiKey}}
content-type: application/json

###
# Create Main Wallet
POST {{url}}/users/main-wallet
Authorization: Bearer {{sessionTokenResponse.response.body.sessionToken}}
content-type: application/json

{
  "userType": "Sender"
}